# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      - run:
          name: create/activate virtual environment
          command: |
            python3 -m venv venv


      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test/requirements.txt

      - run:
          name: run tests
          command: |
            venv/bin/pytest
